//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingPlusJobListener.AccountingAdministration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountingAdministration.AccountingConfiguratorSoap")]
    public interface AccountingConfiguratorSoap {
        
        // CODEGEN: Generating message contract since element name DebugToolStausResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DebugToolStaus", ReplyAction="*")]
        AccountingPlusJobListener.AccountingAdministration.DebugToolStausResponse DebugToolStaus(AccountingPlusJobListener.AccountingAdministration.DebugToolStausRequest request);
        
        // CODEGEN: Generating message contract since element name JobConfigurationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JobConfiguration", ReplyAction="*")]
        AccountingPlusJobListener.AccountingAdministration.JobConfigurationResponse JobConfiguration(AccountingPlusJobListener.AccountingAdministration.JobConfigurationRequest request);
        
        // CODEGEN: Generating message contract since element name AnonymousPrintingStatusResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnonymousPrintingStatus", ReplyAction="*")]
        AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusResponse AnonymousPrintingStatus(AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebugToolStausRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DebugToolStaus", Namespace="http://tempuri.org/", Order=0)]
        public AccountingPlusJobListener.AccountingAdministration.DebugToolStausRequestBody Body;
        
        public DebugToolStausRequest() {
        }
        
        public DebugToolStausRequest(AccountingPlusJobListener.AccountingAdministration.DebugToolStausRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DebugToolStausRequestBody {
        
        public DebugToolStausRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebugToolStausResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DebugToolStausResponse", Namespace="http://tempuri.org/", Order=0)]
        public AccountingPlusJobListener.AccountingAdministration.DebugToolStausResponseBody Body;
        
        public DebugToolStausResponse() {
        }
        
        public DebugToolStausResponse(AccountingPlusJobListener.AccountingAdministration.DebugToolStausResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DebugToolStausResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DebugToolStausResult;
        
        public DebugToolStausResponseBody() {
        }
        
        public DebugToolStausResponseBody(string DebugToolStausResult) {
            this.DebugToolStausResult = DebugToolStausResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JobConfigurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JobConfiguration", Namespace="http://tempuri.org/", Order=0)]
        public AccountingPlusJobListener.AccountingAdministration.JobConfigurationRequestBody Body;
        
        public JobConfigurationRequest() {
        }
        
        public JobConfigurationRequest(AccountingPlusJobListener.AccountingAdministration.JobConfigurationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class JobConfigurationRequestBody {
        
        public JobConfigurationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JobConfigurationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JobConfigurationResponse", Namespace="http://tempuri.org/", Order=0)]
        public AccountingPlusJobListener.AccountingAdministration.JobConfigurationResponseBody Body;
        
        public JobConfigurationResponse() {
        }
        
        public JobConfigurationResponse(AccountingPlusJobListener.AccountingAdministration.JobConfigurationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JobConfigurationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JobConfigurationResult;
        
        public JobConfigurationResponseBody() {
        }
        
        public JobConfigurationResponseBody(string JobConfigurationResult) {
            this.JobConfigurationResult = JobConfigurationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnonymousPrintingStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnonymousPrintingStatus", Namespace="http://tempuri.org/", Order=0)]
        public AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusRequestBody Body;
        
        public AnonymousPrintingStatusRequest() {
        }
        
        public AnonymousPrintingStatusRequest(AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AnonymousPrintingStatusRequestBody {
        
        public AnonymousPrintingStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnonymousPrintingStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnonymousPrintingStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusResponseBody Body;
        
        public AnonymousPrintingStatusResponse() {
        }
        
        public AnonymousPrintingStatusResponse(AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnonymousPrintingStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnonymousPrintingStatusResult;
        
        public AnonymousPrintingStatusResponseBody() {
        }
        
        public AnonymousPrintingStatusResponseBody(string AnonymousPrintingStatusResult) {
            this.AnonymousPrintingStatusResult = AnonymousPrintingStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountingConfiguratorSoapChannel : AccountingPlusJobListener.AccountingAdministration.AccountingConfiguratorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingConfiguratorSoapClient : System.ServiceModel.ClientBase<AccountingPlusJobListener.AccountingAdministration.AccountingConfiguratorSoap>, AccountingPlusJobListener.AccountingAdministration.AccountingConfiguratorSoap {
        
        public AccountingConfiguratorSoapClient() {
        }
        
        public AccountingConfiguratorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingConfiguratorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingConfiguratorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingConfiguratorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountingPlusJobListener.AccountingAdministration.DebugToolStausResponse AccountingPlusJobListener.AccountingAdministration.AccountingConfiguratorSoap.DebugToolStaus(AccountingPlusJobListener.AccountingAdministration.DebugToolStausRequest request) {
            return base.Channel.DebugToolStaus(request);
        }
        
        public string DebugToolStaus() {
            AccountingPlusJobListener.AccountingAdministration.DebugToolStausRequest inValue = new AccountingPlusJobListener.AccountingAdministration.DebugToolStausRequest();
            inValue.Body = new AccountingPlusJobListener.AccountingAdministration.DebugToolStausRequestBody();
            AccountingPlusJobListener.AccountingAdministration.DebugToolStausResponse retVal = ((AccountingPlusJobListener.AccountingAdministration.AccountingConfiguratorSoap)(this)).DebugToolStaus(inValue);
            return retVal.Body.DebugToolStausResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountingPlusJobListener.AccountingAdministration.JobConfigurationResponse AccountingPlusJobListener.AccountingAdministration.AccountingConfiguratorSoap.JobConfiguration(AccountingPlusJobListener.AccountingAdministration.JobConfigurationRequest request) {
            return base.Channel.JobConfiguration(request);
        }
        
        public string JobConfiguration() {
            AccountingPlusJobListener.AccountingAdministration.JobConfigurationRequest inValue = new AccountingPlusJobListener.AccountingAdministration.JobConfigurationRequest();
            inValue.Body = new AccountingPlusJobListener.AccountingAdministration.JobConfigurationRequestBody();
            AccountingPlusJobListener.AccountingAdministration.JobConfigurationResponse retVal = ((AccountingPlusJobListener.AccountingAdministration.AccountingConfiguratorSoap)(this)).JobConfiguration(inValue);
            return retVal.Body.JobConfigurationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusResponse AccountingPlusJobListener.AccountingAdministration.AccountingConfiguratorSoap.AnonymousPrintingStatus(AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusRequest request) {
            return base.Channel.AnonymousPrintingStatus(request);
        }
        
        public string AnonymousPrintingStatus() {
            AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusRequest inValue = new AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusRequest();
            inValue.Body = new AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusRequestBody();
            AccountingPlusJobListener.AccountingAdministration.AnonymousPrintingStatusResponse retVal = ((AccountingPlusJobListener.AccountingAdministration.AccountingConfiguratorSoap)(this)).AnonymousPrintingStatus(inValue);
            return retVal.Body.AnonymousPrintingStatusResult;
        }
    }
}
